### Get all expenses (authenticated)
GET http://localhost:8000/expenses
Content-Type: application/json
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDkxZTI3MjAyZWE0ZTRiZTZjNGMyYyIsImlhdCI6MTc0MjI4MjMyNiwiZXhwIjoxNzQyMzY4NzI2fQ.ZDpd3Kv9rfzadTFictZIHp_0XObrRJq72ip7I673GsI; Max-Age=600; Path=/; Expires=Tue, 18 Mar 2025 07:28:46 GMT; HttpOnly


### Add new expense (authenticated)
POST http://localhost:8000/expenses/add
Content-Type: application/json
Cookie: jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDkxZTI3MjAyZWE0ZTRiZTZjNGMyYyIsImlhdCI6MTc0MjI4MjMyNiwiZXhwIjoxNzQyMzY4NzI2fQ.ZDpd3Kv9rfzadTFictZIHp_0XObrRJq72ip7I673GsI; Max-Age=600; Path=/; Expires=Tue, 18 Mar 2025 07:28:46 GMT; HttpOnly

{
  "title": "Coworking Space",
  "amount": 80.00,
  "category": "Fixed",
  "transactionDate": "2025-03-13",
  "isRecurring": true,
  "recurringFrequency": "monthly",
  "notes": "Hot desk rental"
}



### Edit existing expense (authenticated)
PATCH http://localhost:8000/expenses/67d814141be4524029724fb4
Content-Type: application/json

{
  "amount": 18.99,
  "notes": "Updated monthly fee"
}

### Delete expense (authenticated)
DELETE http://localhost:8000/expenses/<expenseId>

### Expense summary (authenticated)
GET http://localhost:8000/expenses/summary

### Expense summary (authenticated)
GET http://localhost:8000/expenses/recurring


### Get specific expense (authenticated)
GET http://localhost:8000/expenses/67d814b81be4524029724fc2