### Get All Groups for User
GET http://localhost:8000/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM


### Create a New Group
POST http://localhost:8000/groups/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM

{
  "name": "Trip to Greece",
  "description": "Group for organizing our summer trip.",
  "members": ["67d7dc7d6c9a79aa17069853", "67d96e427b59ad430ed81a5e",
  "67d97514b05f1dfb33bd2b27", "67d973bdb05f1dfb33bd2b0b"]
}


### Edit Group Name/Description
PATCH http://localhost:8000/groups/67dbe52998e193da0a69f83d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM

{
  "name": "Greece Trip 2025",
  "description": "Trip to Kefalos."
}


### Delete a Group (Only by Creator)
DELETE http://localhost:8000/groups/67dbe52998e193da0a69f83d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM


### Add a Member to a Group
POST http://localhost:8000/groups/67dbe52998e193da0a69f83d/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM

{
  "memberId": "67d970ef7b59ad430ed81a7e"
}


### Remove a Member from a Group
DELETE http://localhost:8000/groups/67dbe52998e193da0a69f83d/remove
Content-Type: application/json
Authorization: Bearer 


{
  "memberId": "67d970ef7b59ad430ed81a7e"
}


### Get All Expenses for a Group
GET http://localhost:8000/groups/67dbe52998e193da0a69f83d/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDk3M2JkYjA1ZjFkZmIzM2JkMmIwYiIsImlhdCI6MTc0MjQ2NDcwNSwiZXhwIjoxNzQyNTUxMTA1fQ.uV9qnc3C8UEKbOqO1bDkaOdBL-c5j5zFUOKj55G7oEM
