### Register
POST http://localhost:8000/users/register
Content-Type: application/json

{
  "fullName": "john doe",
  "email": "john1@test.com",
  "password": "1234"
}

###

### Login
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "john1@test.com",
  "password": "1234"
}

### Get Profile
GET http://localhost:8000/users/profile



### update profile
PATCH http://localhost:8000/users/profile
Content-Type: application/json

{
  "password": "1234"
}
